const fetchBoard = async() => {
    const res = await fetch("https://sudoku-api.vercel.app/api/dosuku?query={newboard(limit:1){grids{value,solution,difficulty}}}");
    const data = await res.json()
    console.log(JSON.stringify(data, null, 2))   
    // data = {
    //     "newboard": {
    //         "grids": [
    //         {
    //             "value": [
    //             [
    //                 6,
    //                 0,
    //                 4,
    //                 0,
    //                 9,
    //                 2,
    //                 3,
    //                 0,
    //                 1
    //             ],
    //             [
    //                 5,
    //                 1,
    //                 3,
    //                 6,
    //                 0,
    //                 0,
    //                 2,
    //                 9,
    //                 0
    //             ],
    //             [
    //                 9,
    //                 8,
    //                 2,
    //                 0,
    //                 0,
    //                 0,
    //                 0,
    //                 4,
    //                 0
    //             ],
    //             [
    //                 0,
    //                 0,
    //                 0,
    //                 0,
    //                 0,
    //                 0,
    //                 0,
    //                 0,
    //                 0
    //             ],
    //             [
    //                 0,
    //                 3,
    //                 0,
    //                 4,
    //                 0,
    //                 5,
    //                 9,
    //                 0,
    //                 6
    //             ],
    //             [
    //                 4,
    //                 6,
    //                 0,
    //                 9,
    //                 0,
    //                 0,
    //                 8,
    //                 1,
    //                 2
    //             ],
    //             [
    //                 3,
    //                 0,
    //                 0,
    //                 0,
    //                 5,
    //                 0,
    //                 0,
    //                 2,
    //                 0
    //             ],
    //             [
    //                 0,
    //                 0,
    //                 9,
    //                 0,
    //                 0,
    //                 0,
    //                 1,
    //                 3,
    //                 0
    //             ],
    //             [
    //                 8,
    //                 0,
    //                 1,
    //                 0,
    //                 0,
    //                 4,
    //                 0,
    //                 0,
    //                 9
    //             ]
    //             ],
    //             "solution": [
    //             [
    //                 6,
    //                 7,
    //                 4,
    //                 5,
    //                 9,
    //                 2,
    //                 3,
    //                 8,
    //                 1
    //             ],
    //             [
    //                 5,
    //                 1,
    //                 3,
    //                 6,
    //                 4,
    //                 8,
    //                 2,
    //                 9,
    //                 7
    //             ],
    //             [
    //                 9,
    //                 8,
    //                 2,
    //                 3,
    //                 1,
    //                 7,
    //                 6,
    //                 4,
    //                 5
    //             ],
    //             [
    //                 2,
    //                 9,
    //                 7,
    //                 8,
    //                 6,
    //                 1,
    //                 4,
    //                 5,
    //                 3
    //             ],
    //             [
    //                 1,
    //                 3,
    //                 8,
    //                 4,
    //                 2,
    //                 5,
    //                 9,
    //                 7,
    //                 6
    //             ],
    //             [
    //                 4,
    //                 6,
    //                 5,
    //                 9,
    //                 7,
    //                 3,
    //                 8,
    //                 1,
    //                 2
    //             ],
    //             [
    //                 3,
    //                 4,
    //                 6,
    //                 1,
    //                 5,
    //                 9,
    //                 7,
    //                 2,
    //                 8
    //             ],
    //             [
    //                 7,
    //                 5,
    //                 9,
    //                 2,
    //                 8,
    //                 6,
    //                 1,
    //                 3,
    //                 4
    //             ],
    //             [
    //                 8,
    //                 2,
    //                 1,
    //                 7,
    //                 3,
    //                 4,
    //                 5,
    //                 6,
    //                 9
    //             ]
    //             ],
    //             "difficulty": "Medium"
    //         }
    //         ]
    //     }
// }
    return {
        board: data.newboard.grids[0].value,
        solution: data.newboard.grids[0].solution,
        difficulty: data.newboard.grids[0].difficulty
    }
}
 
exports.getBoard = async(difficulty) => {
    let data;
    do{
        data = await fetchBoard();
        console.log("found:", data.difficulty)
        console.log("needed:", difficulty)
        console.log("-------")
    }while(data.difficulty.toLowerCase() != difficulty.toLowerCase())
    return data;
}   
